# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d086ba0d742bf9420d41d6a3373a10faa7f3b32f85f4c95a961be307aae433d7eec53ce57cb6177b4ba070ed2dbef50795141bcea1d9221ab2d70323ca459853

test:
  secret_key_base: f5d9fd70a20b07b5af7757ae10ede8d7aa28af7de2d6a3ec90f6c31ff404402167174c9a197d0d2b201a0c1ff213eead9704732926baa6cb0399a1ed84182659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
